# Default values for backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
tag: "2.0"


postgresql:
  auth:
    database: kanban
    password: vault:kv/data/open-innovation/database#POSTGRE_PASSWORD
    username: vault:kv/data/open-innovation/database#POSTGRE_USER
    postgresPassword: kanban
  primary:
    podAnnotations:
      vault.security.banzaicloud.io/vault-addr: https://dbde-103-110-255-136.ngrok-free.app
      vault.security.banzaicloud.io/vault-role: "open-annovation-ai"
      vault.security.banzaicloud.io/vault-skip-verify: "true"
      vault.security.banzaicloud.io/vault-path: "kubernetes"
  serviceAccount:
    automountServiceAccountToken: true

annotations:
  deployment: 
    vault.security.banzaicloud.io/vault-addr: https://dbde-103-110-255-136.ngrok-free.app
    vault.security.banzaicloud.io/vault-role: "open-annovation-ai"
    vault.security.banzaicloud.io/vault-skip-verify: "true"
    vault.security.banzaicloud.io/vault-path: "kubernetes"
